name = "sevennova-ai"
main = "worker.js"
compatibility_date = "2025-01-01"

[vars]
NEXT_PUBLIC_API_URL = "https://api.sevennova.ai"

[assets]
directory = "out"
not_found_handling = "single-page-application"
binding = "ASSETS"
